name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Debug AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y terraform
      
      - name: Deploy Infrastructure with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
      
      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name demo-cluster
      
      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/app.yaml
          kubectl apply -f k8s/ingress.yaml
